#!/usr/bin/env bash
# Run this from the root directory
cat <<'DESC'
# For testing.

- Run this from the root directory
- You can create testcase using test/make_testcase
  - `test/make_testcase 001`
  - `test/testcase-001/approve`
DESC


cd "$(dirname -- "${BASH_SOURCE[0]}")" || exit
source approvals.bash

tfww=../tfww

describe "command help"
  approve "$tfww --help"
  for subcommand in "switch" "plan" "apply" "push" ; do
    describe "$subcommand command"
      approve "$tfww $subcommand --help"
  done

for __testcase in testcase-*/approve ; do
  if [[ -x "$__testcase" ]]; then
    "$__testcase"
  fi
done
