#!/usr/bin/env bash

cd "$(dirname -- "${BASH_SOURCE[0]}")" || exit
source ../approvals.bash
tfww="../../tfww"

# Write your test code.
describe "testcase-002"

# Setup
it "setup"
mkdir envs plans
terraform init
terraform workspace select default
echo "input-1 = \"first value\""   > envs/test-1.tfvars

describe "plan command"
describe "FILE shoud be envs/*.tfvars"
approve "$tfww plan envs/test-1.tfvars"
[[ -f plans/test-1.tfplan ]] || fail "plan is not exist"

# Cleanup
it "cleanup"
rm -rf envs plans .terraform terraform.tfstate.d
