#!/usr/bin/env bash

cd "$(dirname -- "${BASH_SOURCE[0]}")" || exit
source ../approvals.bash
source ../helpers.bash
tfww="../../tfww"

describe "testcase-003"

setup >/dev/null && pass "setup"

echo "input-1=\"value-1\"" > envs/test-1.tfvars
allow_diff "id *=.*"
approve "$tfww apply envs/test-1.tfvars -y"

echo "input-1=\"value-2\"" > envs/test-1.tfvars
allow_diff "id *=.*"
approve "$tfww plan envs/test-1.tfvars"

allow_diff "id *=.*"
approve "$tfww show plans/test-1.tfplan"

allow_diff "id *=.*"
approve "$tfww show envs/test-1.tfvars"

allow_diff "id *=.*"
approve "$tfww apply plans/test-1.tfplan"

teardown >/dev/null && pass "teardown"
