#!/usr/bin/env bash

cd "$(dirname -- "${BASH_SOURCE[0]}")" || exit
source ../approvals.bash
source ../helpers.bash
tfww="../../tfww"

# Write your test code.
describe "testcase-001"


setup

touch envs/test-{1,3}.tfvars
touch plans/test-{2,3}.tfplan

describe "FILE must should be exist"
approve "$tfww switch envs/nothing.tfvars"
expect_exit_code 1

describe "FILE should be following patterns, below"  

describe "envs/*.tfvars"
approve "$tfww switch envs/test-1.tfvars"
workspace_shoud_be "test-1"

describe "plans/*.tfplan, corresponding tfvars also must be exist"
approve "$tfww switch plans/test-2.tfplan"
workspace_shoud_be "test-1"

approve "$tfww switch plans/test-3.tfplan"
workspace_shoud_be "test-3"

teardown
